"""empty message

Revision ID: 18d96f584d7d
Revises: ff78bf5862fd
Create Date: 2024-04-06 16:55:05.336077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d96f584d7d'
down_revision = 'ff78bf5862fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connection', schema=None) as batch_op:
        batch_op.drop_constraint('connection_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('connection_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user2'], ['email'])
        batch_op.create_foreign_key(None, 'user', ['user1'], ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connection', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('connection_ibfk_2', 'user', ['user2'], ['id'])
        batch_op.create_foreign_key('connection_ibfk_1', 'user', ['user1'], ['id'])

    # ### end Alembic commands ###
