"""empty message

Revision ID: 273b0e812e70
Revises: 32b3114d4496
Create Date: 2024-04-06 17:02:00.697257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273b0e812e70'
down_revision = '32b3114d4496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connection', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user2'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user1'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connection', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
