"""empty message

Revision ID: 35acf003a8d9
Revises: e9d1cc73bc0e
Create Date: 2024-04-06 17:39:16.716786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35acf003a8d9'
down_revision = 'e9d1cc73bc0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isdisabled', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('isdisabled')

    # ### end Alembic commands ###
