"""empty message

Revision ID: 706300313702
Revises: b43369b6d4be
Create Date: 2024-04-06 16:16:01.027082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '706300313702'
down_revision = 'b43369b6d4be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
