"""empty message

Revision ID: b43369b6d4be
Revises: 20f45bc3fa56
Create Date: 2024-04-06 15:55:34.027618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43369b6d4be'
down_revision = '20f45bc3fa56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('profession', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('profession')
        batch_op.drop_column('gender')
        batch_op.drop_column('avatar')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
