"""empty message

Revision ID: e9d1cc73bc0e
Revises: 273b0e812e70
Create Date: 2024-04-06 17:14:01.678322

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9d1cc73bc0e'
down_revision = '273b0e812e70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connection', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connection', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Integer(),
               type_=mysql.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
