"""empty message

Revision ID: ff78bf5862fd
Revises: 9538aa990f46
Create Date: 2024-04-06 16:48:38.567812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff78bf5862fd'
down_revision = '9538aa990f46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user2', sa.Integer(), nullable=True))
        batch_op.drop_constraint('connection_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user2'], ['id'])
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('connection_ibfk_2', 'user', ['parent_id'], ['id'])
        batch_op.drop_column('user2')

    # ### end Alembic commands ###
