"""empty message

Revision ID: d16dcd9571c0
Revises: fba1b5c2a76a
Create Date: 2024-04-06 12:38:02.675077

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd16dcd9571c0'
down_revision = 'fba1b5c2a76a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.drop_column('password')

    with op.batch_alter_table('user', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('phonenumber', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.TEXT(), nullable=True))
        batch_op.drop_column('age')

    # ### end Alembic commands ###
        

